### ISSUE TITLE
Create contirbuting file

### ISSUE THREAD

**Issue by tieandrews** [UBC-MDS/customer_complaint_analyzer#3]
It is a good practice to include information about how others can contribute to your project somewhere in your repository. This is typically done as a separate file in a repo called CONTRIBUTING.md. Here are some examples of this file:

[Altair](https://github.com/altair-viz/altair/blob/master/CONTRIBUTING.md)

[dplyr](https://github.com/tidyverse/dplyr/blob/master/.github/CONTRIBUTING.md)

[Atom editor](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) (very comprehensive)

**Comment by 1124301416** [comment]
contributing file created and committed in the branch ly-contributing-file
