### ISSUE TITLE
Compile reasearch questions into README.md project proposal 

### ISSUE THREAD

**Issue by tieandrews** [UBC-MDS/customer_complaint_analyzer#5]
Identify a data set, research question, & plan of action for analysis to answer that question
Choose a public data set from the web that you are interested in to carry out a small data analysis. You may also use any data set we have previously worked with in MDS. Correctly cite where your data set is coming from in your proposal. The data for the project should be publicly available, and clearly licensed to be shared and used openly on the internet.

With your data set, identify one main predictive or inferential research question that you will attempt to answer with analyses and visualizations (more on this below). Clearly state the research question and any natural sub-questions you need to address, and their type.

Make a plan of how you will analyze the data (report an estimate and confidence intervals? hypothesis test? classification with a decision tree?). Choose something you already learned how to do in another MDS course.

Discuss at least one exploratory data analysis (EDA) table and one exploratory data analysis figure you will create that makes sense for your research question, the data that you have, and the analysis you plan to do.

Suggest how you would share the results of your analysis as one or more tables and/or figures.

Your proposal will be written in the README.md file. You should include there:

the project title

the list of contributors/authors

the project proposal (view from 10,000 feet) with your research question and describing points 1 - 5 listed above.

the names of the licenses contained in LICENSE.md

**Comment by 1124301416** [comment]
completed the first draft

**Comment by tieandrews** [comment]
Completed for MS 1
