### ISSUE TITLE
FEEDBACK: Write 3-5 tests and document what they're testing

### ISSUE THREAD

**Issue by tieandrews** [UBC-MDS/customer_complaint_analyzer#62]

**Comment by tieandrews** [comment]
Functions  should check for correct input types with try/excpet etc.

**Comment by tieandrews** [comment]
TY - Data Loading?processing tests commits: https://github.com/UBC-MDS/customer_complaint_analyzer/pull/70

**Comment by lukeyf** [comment]
analysis and get_dataset's tests added https://github.com/UBC-MDS/customer_complaint_analyzer/pull/76

**Comment by dhruvinishar** [comment]
Added test to check the correct return types of the functions PR #79
